import Vue from "vue";
import Vuetify, {
  VApp,
  VAlert,
  VDialog,
  VSpeedDial,
  VFlex,
  VToolbar,
  VToolbarSideIcon,
  VToolbarTitle,
  VToolbarItems,
  VTooltip,
  VIcon,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VWindow,
  VWindowItem,
  VExpansionPanel,
  VExpansionPanelContent,
  VTextField,
  VForm,
  VSnackbar,
  VImg,
  VBtn,
  VSpacer,
  VDivider,
  VAvatar,
  VFadeTransition
} from "vuetify/lib";
import "vuetify/src/stylus/app.styl";

Vue.use(Vuetify, {
  components: {
    VApp,
    VAlert,
    VDialog,
    VSpeedDial,
    VFlex,
    VToolbar,
    VToolbarSideIcon,
    VToolbarTitle,
    VToolbarItems,
    VTooltip,
    VIcon,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VWindow,
    VWindowItem,
    VExpansionPanel,
    VExpansionPanelContent,
    VTextField,
    VForm,
    VSnackbar,
    VImg,
    VBtn,
    VSpacer,
    VDivider,
    VAvatar,
    VFadeTransition
  },
  iconfont: "md"
});
